# Generated by Django 5.1.1 on 2025-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_customer_email_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="identifier",
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
