# Generated by Django 5.1.1 on 2025-03-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_poll_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="cut_off",
        ),
    ]
