# Generated by Django 5.1.1 on 2025-03-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_poll_cut_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="cut_off",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
