# Generated by Django 5.1.1 on 2025-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_poll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="chart_type",
            field=models.CharField(
                choices=[("barChart", "Bar Chart"), ("pieChart", "Pie Chart")],
                default="barChart",
                max_length=10,
            ),
        ),
    ]
